---
#kind: Namespace
#apiVersion: v1
#metadata:
#  name: aac-monitoring
#  labels:
#    name: aac-monitoring
#---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: aac-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: aac-monitoring
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
