{
 "title": "AMD GPU Node Metrics Overview",
 "description": "AMD GPU Metrics based on the rocm-rdc prometheus plugin and fluent-bit metrics from github.com/ROCm/rdc",
 "tags": [
  "amd",
  "rocm-smi",
  "amd-rocm-rdc",
  "prometheus",
  "<site>"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "amd_smi_gpu_series_info",
    "label": "GPU",
    "query": "AMD Instinct™ MI250 Accelerators"
   },
   { "name": "amd_smi_gpu_driver_version", "query": "6.2.4" },
   { "name": "amd_smi_gpu_vbios_version", "query": "113-D65209-073" },
   { "name": "node", "label": "Host", "query": { "query": "label_values(short_instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "text",
   "description": "The official product name of the AMD GPU series. This is an alphanumeric string.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"color: #73BF68; font-weight: bold\">\n    ${amd_smi_gpu_series_info}\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "P-State",
   "type": "stat",
   "description": "The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance).",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "description": "Percent of average current GPUs usage across all the nodes to indicate how busy the respective blocks are. For --showuse (gpu_busy_percent sysfs file), the SMU samples every ms or so to see if any GPU block (RLC, MEC, PFP, CP) is busy.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gpu_util{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "gauge",
   "description": "Show current Average Graphics Package Power Consumption with --showpower. \"Graphics Package\" refers to the GPU plus any HBM (High-Bandwidth memory) modules, if present.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(power_usage{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "description": "Show average GPU temperature using --showtemp in degrees Celsius. Temperature (Sensor junction) (C) often referred to as the \"Tjunction\" measures the highest operational temperature and is critical for understanding thermal throttling conditions.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gpu_temp{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Temparature",
   "type": "gauge",
   "description": "Show average Memory temperature using --showtemp in degrees Celsius. Temperature (Sensor memory) (C) measures the temperature of the GPU’s memory (VRAM)",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(memory_temp{short_instance=~\"${node:regex}\"}) / 1000",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "table",
   "description": "Assesses the health of active GPU nodes, highlighting any discrepancies such as offline or drained nodes",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_health{short_instance=~\"${node:regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "text",
   "description": "The kernel driver version of the installed AMD display driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": {
    "content": "<div style=\"color: #73BF68; font-weight:bold\">\n    ${amd_smi_gpu_driver_version}\n</div>"
   }
  },
  {
   "title": "Vbios Version",
   "type": "text",
   "description": "The BIOS of the GPU board.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": {
    "content": "<div style=\"color: #73BF68; font-weight:bold\">\n    ${amd_smi_gpu_vbios_version}\n</div>"
   },
   "targets": [
    { "legendFormat": "{{vbios_version}}" }
   ]
  },
  {
   "title": "PCI Express Bandwidth",
   "type": "stat",
   "description": "Average PCIe bandwidth or transfer rate using  amd-smi metric --pcie in gigabytes/sec. amd-smi reports  instantaneous, bidirectional bandwidth, measured in small intervals.\n\nScale-out network bandwidth 8 PCIe® Gen 5 x16 (128 GB/s) per GPU.\n\n\"8 PCIe® Gen 5 or Gen4 x16 (128 GB/s) per GPU\" indicates that each AMD GPU can support up to 8 PCIe Gen 5 or Gen 4 slots, with each slot having 16 lanes total data transfer bandwidth per GPU. PCIe Gen 5 x16 can achieve up to 16 GB/s of data transfer per direction (32 GB/s bidirectional). With 8 such connections, the total bandwidth is 8 x 16 GB/s = 128 GB/s.\n\nInformation about factors that are reducing the frequency of clocks. If all throttle reasons are returned as \"Not Active\" it means that clocks are running as high as possible.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "GPU Clock Speed",
   "type": "gauge",
   "description": "Average frequency of GPU graphics (shader) clock using  --showgpuclocks in hertz\n",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gpu_clock{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "gauge",
   "description": "Average frequency of memory clock using --showclocks in hertz",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(mem_clock{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "stat",
   "description": "Total memory allocated by active contexts / Total installed memory of the GPU instance.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gpu_memory_total{short_instance=~\"${node:regex}\"})",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "description": "Show current GPU memory used in percentage with --showmemuse. For detailed memory usage information for given block(s) TYPEs (vram, vis_vram, gtt) use --showmeminfo will show the amount of VRAM used as well as the total available for those partitions",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gpu_memory_usage{short_instance=~\"${node:regex}\"})/sum(gpu_memory_total{short_instance=~\"${node:regex}\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(gpu_memory_total{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "bargauge",
   "description": "Core GPU (Sensor junction) temperature in degree C.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(gpu_temp{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "Last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(power_usage{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Temparature",
   "type": "bargauge",
   "description": "GPU’s memory VRAM (Sensor memory) temperature in degree C",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(memory_temp{short_instance=~\"${node:regex}\"}) by (short_instance) / 1000",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Current GPUs usage across all the nodes.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(gpu_util{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "avg(gpu_clock{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg(mem_clock{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}}"
    }
   ]
  },
  {
   "title": "PCI Express Transmit and Receive",
   "type": "timeseries",
   "description": "Show PCIe Tx and Rx (PCI Express Transmit and Receive) utilization with --showbw",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(pcie_tx{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}} - PCIe Tx"
    },
    {
     "expr": "avg(pcie_rx{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}} - PCIe Rx"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "barchart",
   "description": "Show current GPU memory used by active contexts",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(gpu_memory_usage{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}} - Memory Usage"
    },
    {
     "expr": "sum(gpu_memory_total{short_instance=~\"${node:regex}\"}) by (short_instance)",
     "legendFormat": "{{short_instance}} - Memory Total"
    },
    {
     "expr": "sum(gpu_memory_usage{short_instance=~\"${node:regex}\"}) by (short_instance)/sum(gpu_memory_total{short_instance=~\"${node:regex}\"}) by (short_instance) * 100",
     "legendFormat": "{{short_instance}} - % Utilization"
    }
   ]
  }
 ]
}