{
 "title": "AMD GPU Node Performance Insights",
 "description": "Embedded Dashboard to visualize node level GPU insights using rocm-smi and rdc",
 "tags": [
  "amd",
  "amd-rocm-rdc",
  "rocm-smi",
  "amd-gpu",
  "prometheus",
  "aac9.amd.com"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(power_usage,short_instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(power_usage, gpu_index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node GPU Activity Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_util{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU Power Distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "power_usage{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU Temperature Insights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temp{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU Memory Temperature Insights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "memory_temp{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"} / 1000",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU Graphics Clock Speed Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "gpu_clock{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU Memory Clock Speed Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "mem_clock{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  },
  {
   "title": "Node GPU PCIe Traffic Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "pcie_tx{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]-pcie_tx"
    },
    {
     "expr": "pcie_rx{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"}",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]-pcie_rx"
    }
   ]
  },
  {
   "title": "Node GPU Memory Utilization: Active Contexts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_memory_usage{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"} /gpu_memory_total{short_instance=~\"${node:regex}\", gpu_index=~\"${gpu:regex}\"} * 100",
     "legendFormat": "{{short_instance}}-gpu[{{gpu_index}}]"
    }
   ]
  }
 ]
}